### ISSUE TITLE
missing unrar causes metadata tagging to fail

### ISSUE THREAD

**Issue by mnbf9rca** [noinip/docker-mylar#3]
I was getting this error:

> WARNING :: Post-Processing : [META-TAGGER][COMIC-TAGGER][CBR-TO-CBZ] Failed to convert cbr to cbz - check permissions on folder : /opt/mylar/cache/ and/or the location where Mylar is trying to tag the files from.

Looking at the issues:
[https://github.com/evilhero/mylar/issues/1283](https://github.com/evilhero/mylar/issues/1283)
i see that it's an unrar issue, so i entered the container (`docker exec -t -i Mylar bash -l`) and installed unrar (`apt-get install unrar`), then changed `unrar_cmd = none` to `unrar_cmd = /usr/bin/unrar` in `config.ini`, it all works fine for now.

Can you please add unrar to your build script?

**Comment by mnbf9rca** [comment]
Just noticed this update - i didnt get any notification. let me update and see how it works now. Thanks!

**Comment by noinip** [comment]
Assuming this is working now
